### ISSUE TITLE
0.36.6 broke stable builds on at least OpenBSD

### ISSUE THREAD

**Issue by niklasha** [bytecodealliance/rustix#506]
0.36.6 has broken builds on OpenBSD, rendering this error on stable 1.65:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/niklas/.cargo/registry/src/github.com-1ecc6299db9ec823/rustix-0.36.6/src/lib.rs:99:26
   |
99 | #![cfg_attr(rustc_attrs, feature(rustc_attrs))]
   |                          ^^^^^^^^^^^^^^^^^^^^
```

Hypothesis: #2667b57d7bdf99d999f5c3eb54e39fa2af2970a2 does only work for Linux, or perhaps for more architectures, but not all.  OpenBSD is a tier 3 architecture though, so there is a chance that the error lies in the rust port.

For now adding the following to Cargo.toml removes the error:
`rustix = "=0.36.5"`

**Comment by sunfishcode** [comment]
We've had a few reports of errors like this which appears to be due to cargo not rerunning the build.rs script when the build configuration changes. Could you try doing a clean build with rustix 0.36.6?

If that fixes it, then any information you have about you build setup and how it might have gotten into this state would be helpful.

**Comment by slonopotamus** [comment]
I also encountered this issue. `cargo clean`/`cargo update` didn't fix the issue. Only `rm -rf ~/.cargo` helped.
