### ISSUE TITLE
rustix v0.35 no longer compiles on s390x-unknown-linux-gnu due to unresolved libc and libc_errno crates

### ISSUE THREAD

**Issue by decathorpe** [bytecodealliance/rustix#439]
Builds using rustix v0.35 (both with default features and with --all-features) on s390x-unknown-linux-gnu now fail with unresolved `use` statements, like:

- no `c` in `backend`
- unresolved import `libc`
- use of undeclared crate or module `libc`
- unresolved import `libc_errno`
- use of undeclared crate or module `libc_errno`

It looks like the reworked target-specific dependencies on libc and libc_errno didn't take the big-endian s390x target into account, where the libc backend apparently also needs to be used?

Full error output when running `cargo build` for rustix v0.35.12 on s390x-unknown-linux-gnu:

```
error[E0432]: unresolved import `c`
 --> src/backend/libc/process/wait.rs:3:16
  |
3 | pub(crate) use c::{
  |                ^ use of undeclared crate or module `c`
error[E0432]: unresolved import `super::c`
 --> src/backend/libc/conv.rs:7:5
  |
7 | use super::c;
  |     ^^^^^^^^ no `c` in `backend`
error[E0432]: unresolved import `super::c`
 --> src/backend/libc/offset.rs:4:5
  |
4 | use super::c;
  |     ^^^^^^^^ no `c` in `backend`
error[E0432]: unresolved import `libc`
  --> src/backend/libc/mod.rs:56:16
   |
56 | pub(crate) use libc as c;
   |                ^^^^^^^^^ no external crate `libc`
error[E0432]: unresolved import `libc_errno`
 --> src/backend/libc/io/errno.rs:7:5
  |
7 | use libc_errno::errno;
  |     ^^^^^^^^^^ use of undeclared crate or module `libc_errno`
error[E0432]: unresolved import `libc`
   --> src/backend/libc/weak.rs:139:17
    |
139 |               use libc::*;
    |                   ^^^^ use of undeclared crate or module `libc`
    |
   ::: src/backend/libc/offset.rs:91:1
    |
91  | / weak_or_syscall! {
92  | |     fn prlimit64(
93  | |         pid: c::pid_t,
94  | |         resource: c::__rlimit_resource_t,
...   |
97  | |     ) via SYS_prlimit64 -> c::c_int
98  | | }
    | |_- in this macro invocation
    |
    = note: this error originates in the macro `syscall` which comes from the expansion of the macro `weak_or_syscall` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0432]: unresolved import `libc`
   --> src/backend/libc/weak.rs:139:17
    |
139 |               use libc::*;
    |                   ^^^^ use of undeclared crate or module `libc`
    |
   ::: src/backend/libc/fs/syscalls.rs:333:5
    |
333 | /     weak_or_syscall! {
334 | |         fn renameat2(
335 | |             olddirfd: c::c_int,
336 | |             oldpath: *const c::c_char,
...   |
340 | |         ) via SYS_renameat2 -> c::c_int
341 | |     }
    | |_____- in this macro invocation
    |
    = note: this error originates in the macro `syscall` which comes from the expansion of the macro `weak_or_syscall` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0432]: unresolved import `libc`
    --> src/backend/libc/weak.rs:139:17
     |
139  |               use libc::*;
     |                   ^^^^ use of undeclared crate or module `libc`
     |
    ::: src/backend/libc/fs/syscalls.rs:1252:5
     |
1252 | /     weak_or_syscall! {
1253 | |         fn memfd_create(
1254 | |             name: *const c::c_char,
1255 | |             flags: c::c_uint
1256 | |         ) via SYS_memfd_create -> c::c_int
1257 | |     }
     | |_____- in this macro invocation
     |
     = note: this error originates in the macro `syscall` which comes from the expansion of the macro `weak_or_syscall` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0432]: unresolved imports `libc`, `super::offset::libc_off_t`, `super::super::offset::libc_fallocate`, `super::super::offset::libc_posix_fadvise`, `super::super::offset::libc_fstat`, `super::super::offset::libc_fstatat`, `super::super::offset::libc_ftruncate`, `super::super::offset::libc_lseek`, `super::super::offset::libc_off_t`, `super::super::offset::libc_fstatfs`, `super::super::offset::libc_statfs`, `super::super::offset::libc_fstatvfs`, `super::super::offset::libc_statvfs`, `super::super::offset::libc_openat`, `super::super::offset::libc_pread`, `super::super::offset::libc_pwrite`, `super::super::offset::libc_preadv`, `super::super::offset::libc_pwritev`, `super::super::offset::libc_preadv2`, `super::super::offset::libc_pwritev2`, `super::super::offset::libc_getrlimit`, `super::super::offset::libc_rlimit`, `super::super::offset::libc_setrlimit`
    --> src/backend/libc/weak.rs:139:17
     |
139  |               use libc::*;
     |                   ^^^^ use of undeclared crate or module `libc`
     |
    ::: src/backend/libc/conv.rs:10:5
     |
10   |   use super::offset::libc_off_t;
     |       ^^^^^^^^^^^^^^^^^^^^^^^^^
     |
    ::: src/backend/libc/fs/syscalls.rs:10:5
     |
10   |   use super::super::offset::libc_fallocate;
     |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
22   |   use super::super::offset::libc_posix_fadvise;
     |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
38   |   use super::super::offset::{libc_fstat, libc_fstatat, libc_ftruncate, libc_lseek, libc_off_t};
     |                              ^^^^^^^^^^  ^^^^^^^^^^^^  ^^^^^^^^^^^^^^  ^^^^^^^^^^  ^^^^^^^^^^
...
47   |   use super::super::offset::{libc_fstatfs, libc_statfs};
     |                              ^^^^^^^^^^^^  ^^^^^^^^^^^
...
55   |   use super::super::offset::{libc_fstatvfs, libc_statvfs};
     |                              ^^^^^^^^^^^^^  ^^^^^^^^^^^^
...
161  |   use {super::super::offset::libc_openat, crate::fs::AtFlags};
     |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
1496 | /     weak_or_syscall! {
1497 | |         pub(super) fn statx(
1498 | |             pirfd: BorrowedFd<'_>,
1499 | |             path: *const c::c_char,
...    |
1503 | |         ) via SYS_statx -> c::c_int
1504 | |     }
     | |_____- in this macro invocation
     |
    ::: src/backend/libc/io/syscalls.rs:9:28
     |
9    |   use super::super::offset::{libc_pread, libc_pwrite};
     |                              ^^^^^^^^^^  ^^^^^^^^^^^
10   |   #[cfg(not(any(target_os = "haiku", target_os = "redox", target_os = "solaris")))]
11   |   use super::super::offset::{libc_preadv, libc_pwritev};
     |                              ^^^^^^^^^^^  ^^^^^^^^^^^^
12   |   #[cfg(all(target_os = "linux", target_env = "gnu"))]
13   |   use super::super::offset::{libc_preadv2, libc_pwritev2};
     |                              ^^^^^^^^^^^^  ^^^^^^^^^^^^^
     |
    ::: src/backend/libc/process/syscalls.rs:26:28
     |
26   |       super::super::offset::{libc_getrlimit, libc_rlimit, libc_setrlimit, LIBC_RLIM_INFINITY},
     |                              ^^^^^^^^^^^^^^  ^^^^^^^^^^^  ^^^^^^^^^^^^^^
     |
     = note: this error originates in the macro `syscall` which comes from the expansion of the macro `weak_or_syscall` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0433]: failed to resolve: use of undeclared crate or module `libc`
   --> src/backend/libc/weak.rs:114:5
    |
114 |     libc::dlsym(libc::RTLD_DEFAULT, name.as_ptr().cast())
    |     ^^^^ use of undeclared crate or module `libc`
error[E0433]: failed to resolve: use of undeclared crate or module `libc`
   --> src/backend/libc/weak.rs:114:17
    |
114 |     libc::dlsym(libc::RTLD_DEFAULT, name.as_ptr().cast())
    |                 ^^^^ use of undeclared crate or module `libc`
error[E0433]: failed to resolve: use of undeclared crate or module `libc`
    --> src/backend/libc/fs/syscalls.rs:1529:34
     |
1529 |     const STATX__RESERVED: u32 = libc::STATX__RESERVED as u32;
     |                                  ^^^^ use of undeclared crate or module `libc`
error[E0433]: failed to resolve: use of undeclared crate or module `libc`
   --> src/backend/libc/fs/types.rs:816:26
    |
816 |         const MANDLOCK = libc::ST_MANDLOCK as u64;
    |                          ^^^^ use of undeclared crate or module `libc`
error[E0433]: failed to resolve: use of undeclared crate or module `libc`
   --> src/backend/libc/fs/types.rs:820:25
    |
820 |         const NOATIME = libc::ST_NOATIME as u64;
    |                         ^^^^ use of undeclared crate or module `libc`
error[E0433]: failed to resolve: use of undeclared crate or module `libc`
   --> src/backend/libc/fs/types.rs:824:23
    |
824 |         const NODEV = libc::ST_NODEV as u64;
    |                       ^^^^ use of undeclared crate or module `libc`
error[E0433]: failed to resolve: use of undeclared crate or module `libc`
   --> src/backend/libc/fs/types.rs:828:28
    |
828 |         const NODIRATIME = libc::ST_NODIRATIME as u64;
    |                            ^^^^ use of undeclared crate or module `libc`
error[E0433]: failed to resolve: use of undeclared crate or module `libc`
   --> src/backend/libc/fs/types.rs:832:24
    |
832 |         const NOEXEC = libc::ST_NOEXEC as u64;
    |                        ^^^^ use of undeclared crate or module `libc`
error[E0433]: failed to resolve: use of undeclared crate or module `libc`
   --> src/backend/libc/fs/types.rs:835:24
    |
835 |         const NOSUID = libc::ST_NOSUID as u64;
    |                        ^^^^ use of undeclared crate or module `libc`
error[E0433]: failed to resolve: use of undeclared crate or module `libc`
   --> src/backend/libc/fs/types.rs:838:24
    |
838 |         const RDONLY = libc::ST_RDONLY as u64;
    |                        ^^^^ use of undeclared crate or module `libc`
error[E0433]: failed to resolve: use of undeclared crate or module `libc`
   --> src/backend/libc/fs/types.rs:842:26
    |
842 |         const RELATIME = libc::ST_RELATIME as u64;
    |                          ^^^^ use of undeclared crate or module `libc`
error[E0433]: failed to resolve: use of undeclared crate or module `libc`
   --> src/backend/libc/fs/types.rs:846:29
    |
846 |         const SYNCHRONOUS = libc::ST_SYNCHRONOUS as u64;
    |                             ^^^^ use of undeclared crate or module `libc`
error[E0433]: failed to resolve: use of undeclared crate or module `libc_errno`
   --> src/backend/libc/process/syscalls.rs:226:5
    |
226 |     libc_errno::set_errno(libc_errno::Errno(0));
    |     ^^^^^^^^^^ use of undeclared crate or module `libc_errno`
error[E0433]: failed to resolve: use of undeclared crate or module `libc_errno`
   --> src/backend/libc/process/syscalls.rs:226:27
    |
226 |     libc_errno::set_errno(libc_errno::Errno(0));
    |                           ^^^^^^^^^^ use of undeclared crate or module `libc_errno`
error[E0433]: failed to resolve: use of undeclared crate or module `libc_errno`
   --> src/backend/libc/process/syscalls.rs:228:8
    |
228 |     if libc_errno::errno().0 != 0 {
    |        ^^^^^^^^^^ use of undeclared crate or module `libc_errno`
error[E0433]: failed to resolve: use of undeclared crate or module `libc_errno`
   --> src/backend/libc/process/syscalls.rs:238:5
    |
238 |     libc_errno::set_errno(libc_errno::Errno(0));
    |     ^^^^^^^^^^ use of undeclared crate or module `libc_errno`
error[E0433]: failed to resolve: use of undeclared crate or module `libc_errno`
   --> src/backend/libc/process/syscalls.rs:238:27
    |
238 |     libc_errno::set_errno(libc_errno::Errno(0));
    |                           ^^^^^^^^^^ use of undeclared crate or module `libc_errno`
error[E0433]: failed to resolve: use of undeclared crate or module `libc_errno`
   --> src/backend/libc/process/syscalls.rs:240:8
    |
240 |     if libc_errno::errno().0 != 0 {
    |        ^^^^^^^^^^ use of undeclared crate or module `libc_errno`
error[E0433]: failed to resolve: use of undeclared crate or module `libc_errno`
   --> src/backend/libc/process/syscalls.rs:250:5
    |
250 |     libc_errno::set_errno(libc_errno::Errno(0));
    |     ^^^^^^^^^^ use of undeclared crate or module `libc_errno`
error[E0433]: failed to resolve: use of undeclared crate or module `libc_errno`
   --> src/backend/libc/process/syscalls.rs:250:27
    |
250 |     libc_errno::set_errno(libc_errno::Errno(0));
    |                           ^^^^^^^^^^ use of undeclared crate or module `libc_errno`
error[E0433]: failed to resolve: use of undeclared crate or module `libc_errno`
   --> src/backend/libc/process/syscalls.rs:252:8
    |
252 |     if libc_errno::errno().0 != 0 {
    |        ^^^^^^^^^^ use of undeclared crate or module `libc_errno`
error[E0433]: failed to resolve: use of undeclared crate or module `libc_errno`
   --> src/backend/libc/process/syscalls.rs:262:5
    |
262 |     libc_errno::set_errno(libc_errno::Errno(0));
    |     ^^^^^^^^^^ use of undeclared crate or module `libc_errno`
error[E0433]: failed to resolve: use of undeclared crate or module `libc_errno`
   --> src/backend/libc/process/syscalls.rs:262:27
    |
262 |     libc_errno::set_errno(libc_errno::Errno(0));
    |                           ^^^^^^^^^^ use of undeclared crate or module `libc_errno`
error[E0433]: failed to resolve: use of undeclared crate or module `libc_errno`
   --> src/backend/libc/process/syscalls.rs:264:8
    |
264 |     if libc_errno::errno().0 != 0 {
    |        ^^^^^^^^^^ use of undeclared crate or module `libc_errno`
error[E0425]: cannot find function `syscall` in this scope
   --> src/backend/libc/weak.rs:187:13
    |
187 |               syscall($sys_name, $($arg_name.into_syscall_arg()),*) as $ret
    |               ^^^^^^^ not found in this scope
    |
   ::: src/backend/libc/offset.rs:91:1
    |
91  | / weak_or_syscall! {
92  | |     fn prlimit64(
93  | |         pid: c::pid_t,
94  | |         resource: c::__rlimit_resource_t,
...   |
97  | |     ) via SYS_prlimit64 -> c::c_int
98  | | }
    | |_- in this macro invocation
    |
    = note: this error originates in the macro `syscall` which comes from the expansion of the macro `weak_or_syscall` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0425]: cannot find value `SYS_prlimit64` in this scope
   --> src/backend/libc/offset.rs:97:11
    |
97  |     ) via SYS_prlimit64 -> c::c_int
    |           ^^^^^^^^^^^^^ help: a function with a similar name exists: `prlimit64`
    |
   ::: src/backend/libc/weak.rs:136:9
    |
136 |         unsafe fn $name($($arg_name:$t),*) -> $ret {
    |         ------------------------------------------ similarly named function `prlimit64` defined here
error[E0425]: cannot find function `syscall` in this scope
   --> src/backend/libc/weak.rs:187:13
    |
187 |               syscall($sys_name, $($arg_name.into_syscall_arg()),*) as $ret
    |               ^^^^^^^ not found in this scope
    |
   ::: src/backend/libc/fs/syscalls.rs:333:5
    |
333 | /     weak_or_syscall! {
334 | |         fn renameat2(
335 | |             olddirfd: c::c_int,
336 | |             oldpath: *const c::c_char,
...   |
340 | |         ) via SYS_renameat2 -> c::c_int
341 | |     }
    | |_____- in this macro invocation
    |
    = note: this error originates in the macro `syscall` which comes from the expansion of the macro `weak_or_syscall` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0425]: cannot find value `SYS_renameat2` in this scope
   --> src/backend/libc/fs/syscalls.rs:340:15
    |
340 |         ) via SYS_renameat2 -> c::c_int
    |               ^^^^^^^^^^^^^ help: a function with a similar name exists: `renameat2`
    |
   ::: src/backend/libc/weak.rs:136:9
    |
136 |         unsafe fn $name($($arg_name:$t),*) -> $ret {
    |         ------------------------------------------ similarly named function `renameat2` defined here
error[E0425]: cannot find function `syscall` in this scope
    --> src/backend/libc/weak.rs:187:13
     |
187  |               syscall($sys_name, $($arg_name.into_syscall_arg()),*) as $ret
     |               ^^^^^^^ not found in this scope
     |
    ::: src/backend/libc/fs/syscalls.rs:1252:5
     |
1252 | /     weak_or_syscall! {
1253 | |         fn memfd_create(
1254 | |             name: *const c::c_char,
1255 | |             flags: c::c_uint
1256 | |         ) via SYS_memfd_create -> c::c_int
1257 | |     }
     | |_____- in this macro invocation
     |
     = note: this error originates in the macro `syscall` which comes from the expansion of the macro `weak_or_syscall` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0425]: cannot find value `SYS_memfd_create` in this scope
    --> src/backend/libc/fs/syscalls.rs:1256:15
     |
1256 |         ) via SYS_memfd_create -> c::c_int
     |               ^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `memfd_create`
     |
    ::: src/backend/libc/weak.rs:136:9
     |
136  |         unsafe fn $name($($arg_name:$t),*) -> $ret {
     |         ------------------------------------------ similarly named function `memfd_create` defined here
error[E0425]: cannot find function `syscall` in this scope
    --> src/backend/libc/weak.rs:187:13
     |
187  |               syscall($sys_name, $($arg_name.into_syscall_arg()),*) as $ret
     |               ^^^^^^^ not found in this scope
     |
    ::: src/backend/libc/fs/syscalls.rs:1496:5
     |
1496 | /     weak_or_syscall! {
1497 | |         pub(super) fn statx(
1498 | |             pirfd: BorrowedFd<'_>,
1499 | |             path: *const c::c_char,
...    |
1503 | |         ) via SYS_statx -> c::c_int
1504 | |     }
     | |_____- in this macro invocation
     |
     = note: this error originates in the macro `syscall` which comes from the expansion of the macro `weak_or_syscall` (in Nightly builds, run with -Z macro-backtrace for more info)
error[E0425]: cannot find value `SYS_statx` in this scope
    --> src/backend/libc/fs/syscalls.rs:1503:15
     |
1503 |         ) via SYS_statx -> c::c_int
     |               ^^^^^^^^^ not found in this scope
warning: unused import: `core::convert::TryInto`
  --> src/backend/libc/process/cpu_set.rs:47:9
   |
47 |     use core::convert::TryInto;
   |         ^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default
Some errors have detailed explanations: E0425, E0432, E0433.
For more information about an error, try `rustc --explain E0425`.
warning: `rustix` (lib) generated 1 warning
error: could not compile `rustix` due to 41 previous errors; 1 warning emitted
```

**Comment by decathorpe** [comment]
Damn, you're right. I should have checked changes I made more carefully before submitting this issue.

Turns out this was caused by buggy tooling on our side. We drop dependencies for non-linux targets for Fedora package builds, because we don't want to package crates which will end up unused (like winapi or windows-sys) - and it looks like the algorithm we use to evaluate `cfg('foo')` expressions for target-scoped dependencies is subtly wrong in this case - possibly because it doesn't know the custom "rustix_use_libc" cfg option, as it's not a standard abbreviation like `windows` or `unix`.

Either way, that's a bug on our side, not in rustix. So, sorry for the noise, and thanks for the fast response!

**Comment by Artimus100** [comment]
Hey  @decathorpe  any idea on how to solve these 
error[E0432]: unresolved import libc_errno
--> /Users/artimus100/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.34/src/backend/libc/fs/dir.rs:39:5
|
39 | use libc_errno::{errno, set_errno, Errno};
| ^^^^^^^^^^ use of undeclared crate or module libc_errno

error[E0432]: unresolved import libc_errno
--> /Users/artimus100/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.34/src/backend/libc/io/errno.rs:7:5
|
7 | use libc_errno::errno;
| ^^^^^^^^^^ use of undeclared crate or module libc_errno

error[E0433]: failed to resolve: use of undeclared crate or module libc_errno
--> /Users/artimus100/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.34/src/weak.rs:263:17
|
263 | libc_errno::set_errno(libc_errno::Errno(libc::ENOSYS));
| ^^^^^^^^^^ use of undeclared crate or module libc_errno
|
::: /Users/artimus100/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.34/src/backend/libc/c.rs:305:5
|
305 | / weakcall! {
306 | | pub(in super::super) fn preadv(
307 | | fd: libc::c_int,
308 | | iov: *const libc::iovec,
... |
311 | | ) -> libc::ssize_t
312 | | }
| |_____- in this macro invocation
|
= note: this error originates in the macro weakcall (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: use of undeclared crate or module libc_errno
--> /Users/artimus100/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.34/src/weak.rs:263:39
|
263 | libc_errno::set_errno(libc_errno::Errno(libc::ENOSYS));
| ^^^^^^^^^^ use of undeclared crate or module libc_errno
|
::: /Users/artimus100/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.34/src/backend/libc/c.rs:305:5
|
305 | / weakcall! {
306 | | pub(in super::super) fn preadv(
307 | | fd: libc::c_int,
308 | | iov: *const libc::iovec,
... |
311 | | ) -> libc::ssize_t
312 | | }
| |_____- in this macro invocation
|
= note: this error originates in the macro weakcall (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: use of undeclared crate or module libc_errno
--> /Users/artimus100/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.34/src/weak.rs:263:17
|
263 | libc_errno::set_errno(libc_errno::Errno(libc::ENOSYS));
| ^^^^^^^^^^ use of undeclared crate or module libc_errno
|
::: /Users/artimus100/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.34/src/backend/libc/c.rs:313:5
|
313 | / weakcall! {
314 | | pub(in super::super) fn pwritev(
315 | | fd: libc::c_int,
316 | | iov: *const libc::iovec,
317 | | iovcnt: libc::c_int, offset: libc::off_t
318 | | ) -> libc::ssize_t
319 | | }
| |_____- in this macro invocation
|
= note: this error originates in the macro weakcall (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: use of undeclared crate or module libc_errno
--> /Users/artimus100/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.34/src/weak.rs:263:39
|
263 | libc_errno::set_errno(libc_errno::Errno(libc::ENOSYS));
| ^^^^^^^^^^ use of undeclared crate or module libc_errno
|
::: /Users/artimus100/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.34/src/backend/libc/c.rs:313:5
|
313 | / weakcall! {
314 | | pub(in super::super) fn pwritev(
315 | | fd: libc::c_int,
316 | | iov: *const libc::iovec,
317 | | iovcnt: libc::c_int, offset: libc::off_t
318 | | ) -> libc::ssize_t
319 | | }
| |_____- in this macro invocation
|
= note: this error originates in the macro weakcall (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: use of undeclared crate or module libc_errno
--> /Users/artimus100/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.34/src/backend/libc/fs/syscalls.rs:899:38
|
899 | let code = match libc_errno::errno().0 {
| ^^^^^^^^^^ use of undeclared crate or module libc_errno

error[E0433]: failed to resolve: use of undeclared crate or module libc_errno
--> /Users/artimus100/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.34/src/backend/libc/fs/syscalls.rs:922:38
|
922 | let code = match libc_errno::errno().0 {
| ^^^^^^^^^^ use of undeclared crate or module libc_errno

error[E0433]: failed to resolve: use of undeclared crate or module libc_errno
--> /Users/artimus100/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.34/src/weak.rs:155:17
|
155 | libc_errno::set_errno(libc_errno::Errno(libc::ENOSYS));
| ^^^^^^^^^^ use of undeclared crate or module libc_errno
|
::: /Users/artimus100/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.34/src/backend/libc/fs/syscalls.rs:1080:5
|
1080 | / syscall! {
1081 | | fn fclonefileat(
1082 | | srcfd: BorrowedFd<'>,
*1083 | | dst_dirfd: BorrowedFd<'*>,
... |
1086 | | ) via SYS_fclonefileat -> c::c_int
1087 | | }
| |_____- in this macro invocation
|
= note: this error originates in the macro syscall (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: use of undeclared crate or module libc_errno
--> /Users/artimus100/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.34/src/weak.rs:155:39
|
155 | libc_errno::set_errno(libc_errno::Errno(libc::ENOSYS));
| ^^^^^^^^^^ use of undeclared crate or module libc_errno
|
::: /Users/artimus100/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustix-0.38.34/src/backend/libc/fs/syscalls.rs:1080:5
|
1080 | / syscall! {
1081 | | fn fclonefileat(
1082 | | srcfd: BorrowedFd<'>,
*1083 | | dst_dirfd: BorrowedFd<'*>,
... |
1086 | | ) via SYS_fclonefileat -> c::c_int
1087 | | }
| |_____- in this macro invocation
|
= note: this error originates in the macro syscall (in Nightly builds, run with -Z macro-backtrace for more info)

Compiling serde_derive v1.0.204
Compiling zeroize_derive v1.4.2
Compiling zerocopy-derive v0.6.6
Some errors have detailed explanations: E0432, E0433.
For more information about an error, try rustc --explain E0432.
error: could not compile rustix (lib) due to 10 previous errors
