### ISSUE TITLE
Not buildable with macOS <= 10.9

### ISSUE THREAD

**Issue by pkgw** [bytecodealliance/rustix#648]
It seems that Rustix isn't buildable against versions of the macOS SDK <= 10.9, which don't provide some of the `*at` filesystem calls:

```
   = note: Undefined symbols for architecture x86_64:
             "_renameat", referenced from:
                 rustix::backend::fs::syscalls::renameat::h2c0c0bdc5b1b53dd in librustix-8716fc0ada80f679.rlib(rustix-8716fc0ada80f679.rustix.c8295d04-cgu.2.rcgu.o)
             "_unlinkat", referenced from:
                 rustix::backend::fs::syscalls::unlinkat::h64403488044b3003 in librustix-8716fc0ada80f679.rlib(rustix-8716fc0ada80f679.rustix.c8295d04-cgu.2.rcgu.o)
             "_linkat", referenced from:
                 rustix::backend::fs::syscalls::linkat::h944058f8262ceb1d in librustix-8716fc0ada80f679.rlib(rustix-8716fc0ada80f679.rustix.c8295d04-cgu.2.rcgu.o)
           ld: symbol(s) not found for architecture x86_64
           clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```

This is from [a conda-forge build][1] of Tectonic. During package builds, conda-forge sets the `MACOSX_SDK_VERSION` and `MACOSX_DEPLOYMENT_TARGET` environment variables to 10.9 in an effort to produce binaries that are widely portable.

[1]: https://github.com/conda-forge/tectonic-feedstock/pull/60

This is an old OS version, of course, and if there isn't any interest in attaining/maintaining compatibility with it, I'll understand. But I thought I'd flag the issue so it's at least documented.

**Comment by sunfishcode** [comment]
Thanks for the report! Rustix should fix these; I've submitted https://github.com/bytecodealliance/rustix/pull/649 with a fix.

**Comment by pkgw** [comment]
Thanks for looking into this! For what it's worth, I don't know if those three functions are the only ones that aren't available, or if maybe there's some linker magic where there are other potentially problematic symbols but they're not causing errors because they're not used in that particular program.

Also, out of curiosity, what would be the behavior for a build on 10.9 with the weak symbols — failure at runtime?

**Comment by sunfishcode** [comment]
I don't have a macos 10.9 or earlier machine myself, but I have now added `MACOSX_DEPLOYMENT_TARGET` and `MACOSX_SDK_VERSION` to the CI script, and the build succeeds.

I've now modified the PR to fall back to `link`/`rename`/etc. in the cases where that's possible, but otherewise yes, they'll fail at runtime with an `ENOSYS` error.

**Comment by sunfishcode** [comment]
This is now fixed in rustix 0.37.19.
