### ISSUE TITLE
no_std compilation broken when `fs` feature is not enabled

### ISSUE THREAD

**Issue by niluxv** [bytecodealliance/rustix#453]
Compilation fails with the following error when the `fs` and `std` features are not enabled:
```
error[E0433]: failed to resolve: could not find `fs` in the crate root
  --> src/io/fd/owned.rs:95:25
   |
95 |         let fd = crate::fs::fcntl_dupfd_cloexec(self, 0)?;
   |                         ^^ could not find `fs` in the crate root
```

Caused by #449.

**Comment by niluxv** [comment]
Also to catch this kind of regressions earlier, maybe it would be good to have a `cargo check --no-default-features` check in CI.

**Comment by sunfishcode** [comment]
This is fixed in 0.36.3.

**Comment by niluxv** [comment]
Thanks a lot!
