### ISSUE TITLE
Broken builds on loongarch64 with libc 0.2.175

### ISSUE THREAD

**Issue by tgross35** [bytecodealliance/rustix#1496]
There is a new failure on loongarch64 with the new release:

```text
error[E0659]: `STATX_TYPE` is ambiguous
   --> /cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-1.0.8/src/fs/statx.rs:73:25
    |
 73 |         const TYPE = c::STATX_TYPE;
    |                         ^^^^^^^^^^ ambiguous name
    |
    = note: ambiguous because of multiple glob imports of a name in the same module
note: `STATX_TYPE` could refer to the constant imported here
   --> /cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-1.0.8/src/backend/libc/c.rs:7:16
    |
  7 | pub(crate) use libc::*;
    |                ^^^^^^^
    = help: consider adding an explicit import of `STATX_TYPE` to disambiguate
note: `STATX_TYPE` could also refer to the constant imported here
   --> /cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-1.0.8/src/backend/libc/c.rs:512:16
    |
512 | pub(crate) use statx_flags::*;
    |                ^^^^^^^^^^^^^^
    = help: consider adding an explicit import of `STATX_TYPE` to disambiguate
```

(stumbled across this in CI)

I think rustix is assuming that `libc`'s musl version is stuck at a pre-1.2 version. This is a pretty safe assumption, but we have a config that enables 1.2+ API on targets that never supported anything less https://github.com/rust-lang/libc/blob/bbafd450b7b03f0a0248efbae99b563b04bdb10a/build.rs#L91-L97. loongarch is in that boat and the most recent release contained https://github.com/rust-lang/libc/pull/3976, hence this issue.

Unfortunately I don't really have a better suggestion that to use the same logic as our build script to decide whether or not you need the polyfills, or to replace the glob imports.

**Comment by weihanglo** [comment]
Cargo also failed to cross-compile to loongarch64 musl due to this.

https://github.com/rust-lang/rust/pull/145478#issuecomment-3193494156

**Comment by wojiushixiaobai** [comment]
- https://github.com/loong64/uv/actions/runs/17161458278/job/48691559367
```sh
error[E0659]: `STATX_MODE` is ambiguous
   --> /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-1.0.8/src/fs/statx.rs:76:25
    |
76  |         const MODE = c::STATX_MODE;
    |                         ^^^^^^^^^^ ambiguous name
    |
    = note: ambiguous because of multiple glob imports of a name in the same module
note: `STATX_MODE` could refer to the constant imported here
   --> /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-1.0.8/src/backend/libc/c.rs:7:16
    |
7   | pub(crate) use libc::*;
    |                ^^^^^^^
    = help: consider adding an explicit import of `STATX_MODE` to disambiguate
note: `STATX_MODE` could also refer to the constant imported here
   --> /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-1.0.8/src/backend/libc/c.rs:512:16
    |
512 | pub(crate) use statx_flags::*;
    |                ^^^^^^^^^^^^^^
    = help: consider adding an explicit import of `STATX_MODE` to disambiguate

error[E0659]: `STATX_NLINK` is ambiguous
   --> /root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-1.0.8/src/fs/statx.rs:79:26
    |
79  |         const NLINK = c::STATX_NLINK;
    |                          ^^^^^^^^^^^ ambiguous name
    |
    = note: ambiguous because of multiple glob imports of a name in the same module
```

**Comment by tgross35** [comment]
I'm going to leave it up to @sunfishcode to close since a backport to 1.0 was requested above, which I don't think has happened yet.

Also note that this isn't exactly a permanent fix, I believe all musl targets will have the same breakage once libc starts exposing statx. We'll try to coordinate this when that happens, but if there is solution  then that would be better (like creating an internal module for statx flags that reexports from libc without the glob).

**Comment by strophy** [comment]
I'm trying to [enable statx](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/98199) in Rust on Alpine Linux and hitting this issue as well, specifically with ppc64le and s390x. Is there a plan for how to coordinate this between rust, libc, and rustix?

**Comment by xtqqczze** [comment]
I think this was fixed in rustix 1.1.1.

Rustix 1.1.5 includes further `statx_flags`-related changes to avoid musl breakage with libc 0.2.190.
