### ISSUE TITLE
Project using rustix dependency fails to compile with Rust 1.72

### ISSUE THREAD

**Issue by rayokamoto** [bytecodealliance/rustix#849]
I am trying to build a Rust project which uses rustix as a dependency using Rust 1.72 and Bazel, but I get the following error (see attached file for the full log).

```sh
ERROR: /home/ray/.cache/bazel/_bazel_ray/69e8a9a6ddd14a1501afcf5af864a17a/external/crate_index__rustix-0.38.14/BUILD.bazel:22:13: Compiling Rust rlib rustix v0.38.14 (293 files) [for tool] failed: (Exit 1): process_wrapper failed: error executing command (from target @crate_index__rustix-0.38.14//:rustix) bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_rust/util/process_wrapper/process_wrapper --env-file bazel-out/k8-opt-exec-2B5CBBC6/bin/external/crate_index__rustix-0.38.14/rustix_build_script.env ... (remaining 40 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
error[E0432]: unresolved import `linux_raw_sys::general`
  --> external/crate_index__rustix-0.38.14/src/maybe_polyfill/no_std/io/mod.rs:14:20
   |
14 | use linux_raw_sys::general::__kernel_size_t;
   |                    ^^^^^^^ could not find `general` in `linux_raw_sys`

error[E0432]: unresolved import `linux_raw_sys::general`
  --> external/crate_index__rustix-0.38.14/src/backend/linux_raw/conv.rs:50:20
   |
50 | use linux_raw_sys::general::__kernel_loff_t;
   |                    ^^^^^^^ could not find `general` in `linux_raw_sys`

error[E0432]: unresolved import `linux_raw_sys::errno`
  --> external/crate_index__rustix-0.38.14/src/backend/linux_raw/io/errno.rs:17:5
   |
17 | use linux_raw_sys::errno;
   |     ^^^^^^^^^^^^^^^^^^^^ no `errno` in the root
   |
note: found an item that was configured out
  --> external/crate_index__linux-raw-sys-0.4.7/src/lib.rs:196:9
   = note: the item is gated behind the `errno` feature
note: found an item that was configured out
  --> external/crate_index__linux-raw-sys-0.4.7/src/lib.rs:232:9
   = note: the item is gated behind the `errno` feature

# ... etc. (see full log)
```

[compile-error.txt](https://github.com/bytecodealliance/rustix/files/12705683/compile-error.txt)

I have tried compiling the project with Rust 1.70 and 1.71 with the same Bazel build process and it compiles successfully. Furthermore, compiling the project with just `cargo build` also succeeds, regardless of the Rust version.

I suspect that these errors may be related to [Rust reports potentially useful `cfg`-disabled items in errors](https://blog.rust-lang.org/2023/08/24/Rust-1.72.0.html#rust-reports-potentially-useful-cfg-disabled-items-in-errors) which is a new feature in 1.72.

**Comment by rayokamoto** [comment]
Things are compiling fine for me now, I'm not sure what fixed it but it works
