### ISSUE TITLE
Build failure on aarch64-linux-android since 0.35.8

### ISSUE THREAD

**Issue by LingMan** [bytecodealliance/rustix#389]
```
error[E0433]: failed to resolve: use of undeclared crate or module `linux_raw_sys`
    --> /home/laughingman/.cargo/registry/src/github.com-1ecc6299db9ec823/rustix-0.35.8/src/backend/libc/fs/syscalls.rs:1475:34
     |
1475 |     const STATX__RESERVED: u32 = linux_raw_sys::general::STATX__RESERVED;
     |                                  ^^^^^^^^^^^^^ use of undeclared crate or module `linux_raw_sys`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `rustix` due to previous error
```
Must have been introduced in https://github.com/bytecodealliance/rustix/commit/2c6db2e7521a15e9baec47a647c7ff6824970ee7.

**Comment by sunfishcode** [comment]
I'm not able to immediately reproduce this with `cargo check --target=aarch64-linux-android --features=all-apis,use-libc --all-targets`, but I'm continuing to investigate.

**Comment by LingMan** [comment]
You're right. It reproduces with `cargo check --target=aarch64-linux-android --features=termios --all-targets`.

**Comment by LingMan** [comment]
Or even just `cargo check --target=aarch64-linux-android`.

**Comment by sunfishcode** [comment]
I've now submitted #390 with a fix for this.

**Comment by sunfishcode** [comment]
This is now fixed in 0.35.9.

**Comment by LingMan** [comment]
Thanks for taking care of this so quickly.
